### ISSUE TITLE
 Needs a screenshot 

### ISSUE THREAD

**Issue by LeandroStanger** [flathub/com.github.lainsce.timetable#1]
![captura de tela de 2018-12-21 07-21-39](https://user-images.githubusercontent.com/26097419/50334989-b5c4ad00-04e8-11e9-8207-81704e4d5910.png)

**Comment by lainsce** [comment]
It does have a screenshot. Maybe you need to reload appdata?

**Comment by LeandroStanger** [comment]
In Flathub the screen capture does not appear
![captura de tela de 2018-12-21 17-01-30](https://user-images.githubusercontent.com/26097419/50358936-b89bbe00-0539-11e9-8ddb-82770dcc51c4.png)

**Comment by lainsce** [comment]
I don't know how to fix this since it shows in AppCenter properly.

**Comment by LeandroStanger** [comment]
@nedrichards Could help?

**Comment by uajain** [comment]
It still does not have a screenshot for Flathub or other software clients. Also,  I don't see a appdata file in this repo which generally contains screenshot(s) location/URL.

@lainsce Can I help in adding a appdata file? Does the appdata lives somewhere already? 
Thanks

**Comment by lainsce** [comment]
The appdata file lives in Timetable's repo under data.

**Comment by uajain** [comment]
> It still does not have a screenshot for Flathub or other software clients. Also, I don't see a appdata file in this repo which generally contains screenshot(s) location/URL.
> 
> @lainsce Can I help in adding a appdata file? Does the appdata lives somewhere already?
> Thanks

Shoot! The appdata is present in the tarball itself.
